Repository brain-score/vision, pull requests merged in 2024-11, with the labels that each got.

#1434 brain-score.org submission (user:538) | (public:False)
  brainscore_vision/models/cvt_cvt_13_224_in1k_4/__init__.py
  brainscore_vision/models/cvt_cvt_13_224_in1k_4/model.py
  brainscore_vision/models/cvt_cvt_13_224_in1k_4/region_layer_map/cvt_cvt-13-224-in1k_4.json
  brainscore_vision/models/cvt_cvt_13_224_in1k_4/requirements.txt
  brainscore_vision/models/cvt_cvt_13_224_in1k_4/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1400 Layer Mapping Orchestrator (build:115)
  brainscore_vision/models/scaling_models/region_layer_map/convnext_base_imagenet_full_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/convnext_large_imagenet_full_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/convnext_small_imagenet_100_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/convnext_small_imagenet_10_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/convnext_small_imagenet_1_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/convnext_small_imagenet_full_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/deit_base_imagenet_full_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/deit_large_imagenet_full_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/deit_small_imagenet_100_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/deit_small_imagenet_10_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/deit_small_imagenet_1_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/deit_small_imagenet_full_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/efficientnet_b0_imagenet_full.json
  brainscore_vision/models/scaling_models/region_layer_map/efficientnet_b1_imagenet_full.json
  brainscore_vision/models/scaling_models/region_layer_map/efficientnet_b2_imagenet_full.json
  brainscore_vision/models/scaling_models/region_layer_map/resnet101_ecoset_full.json
  brainscore_vision/models/scaling_models/region_layer_map/resnet101_imagenet_full.json
  brainscore_vision/models/scaling_models/region_layer_map/resnet152_ecoset_full.json
  brainscore_vision/models/scaling_models/region_layer_map/resnet18_ecoset_full.json
  brainscore_vision/models/scaling_models/region_layer_map/resnet34_ecoset_full.json
  brainscore_vision/models/scaling_models/region_layer_map/resnet50_ecoset_full.json
  brainscore_vision/models/scaling_models/region_layer_map/resnet50_imagenet_100_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/resnet50_imagenet_10_seed-0.json
  brainscore_vision/models/scaling_models/region_layer_map/resnet50_imagenet_1_seed-0.json
Labels: Skip

#1441 Layer Mapping Orchestrator (build:127)
  brainscore_vision/models/alexnet/region_layer_map/alexnet.json
Labels: mapping-complete

#1443 Layer Mapping Orchestrator (build:128)
  brainscore_vision/models/resnet50_tutorial/region_layer_map/resnet50_tutorial.json
Labels: mapping-complete

#1447 Layer Mapping Orchestrator (build:135)
  brainscore_vision/models/voneresnet_50_non_stochastic/region_layer_map/voneresnet-50-non_stochastic.json
Labels: mapping-complete

#1446 Automated version bumping and pypi package building
  .github/workflows/bump_version.yml
  pyproject.toml
Labels: minor update

#1006 Converted Res2net50_26w_4s
  brainscore_vision/models/Res2Net50_26w_4s/__init__.py
  brainscore_vision/models/Res2Net50_26w_4s/model.py
  brainscore_vision/models/Res2Net50_26w_4s/region_layer_map/Res2Net50_26w_4s.json
  brainscore_vision/models/Res2Net50_26w_4s/requirements.txt
  brainscore_vision/models/Res2Net50_26w_4s/test.py
Labels: mapping-complete

#1189 Converted Clip rn50
  brainscore_vision/models/CLIP-RN50/__init__.py
  brainscore_vision/models/CLIP-RN50/model.py
  brainscore_vision/models/CLIP-RN50/region_layer_map/CLIP-RN50.json
  brainscore_vision/models/CLIP-RN50/requirements.txt
  brainscore_vision/models/CLIP-RN50/test.py
Labels: OOM, mapping-complete

#1134 Converted mobilenet v2 1.0 160
  brainscore_vision/models/mobilenet_v2_1_0_160/__init__.py
  brainscore_vision/models/mobilenet_v2_1_0_160/model.py
  brainscore_vision/models/mobilenet_v2_1_0_160/region_layer_map/mobilenet_v2_1_0_160.json
  brainscore_vision/models/mobilenet_v2_1_0_160/requirements.txt
  brainscore_vision/models/mobilenet_v2_1_0_160/test.py
Labels: mapping-complete

#1130 Converted mobilenet v2 0.5 224
  brainscore_vision/models/mobilenet_v2_0_5_224/__init__.py
  brainscore_vision/models/mobilenet_v2_0_5_224/model.py
  brainscore_vision/models/mobilenet_v2_0_5_224/region_layer_map/mobilenet_v2_0_5_224.json
  brainscore_vision/models/mobilenet_v2_0_5_224/requirements.txt
  brainscore_vision/models/mobilenet_v2_0_5_224/test.py
Labels: mapping-complete

#1182 Convered Imagenet l2 3 0
  brainscore_vision/models/imagenet_l2_3_0/__init__.py
  brainscore_vision/models/imagenet_l2_3_0/model.py
  brainscore_vision/models/imagenet_l2_3_0/requirements.txt
  brainscore_vision/models/imagenet_l2_3_0/test.py
Labels: OOM

#1072 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet18_240719_3/__init__.py
  brainscore_vision/models/yudixie_resnet18_240719_3/model.py
  brainscore_vision/models/yudixie_resnet18_240719_3/region_layer_map/yudixie_resnet18_distance_translation_0_240719.json
  brainscore_vision/models/yudixie_resnet18_240719_3/setup.py
  brainscore_vision/models/yudixie_resnet18_240719_3/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1073 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet18_240719_4/__init__.py
  brainscore_vision/models/yudixie_resnet18_240719_4/model.py
  brainscore_vision/models/yudixie_resnet18_240719_4/region_layer_map/yudixie_resnet18_distance_rotation_0_240719.json
  brainscore_vision/models/yudixie_resnet18_240719_4/setup.py
  brainscore_vision/models/yudixie_resnet18_240719_4/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1074 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet18_240719_5/__init__.py
  brainscore_vision/models/yudixie_resnet18_240719_5/model.py
  brainscore_vision/models/yudixie_resnet18_240719_5/region_layer_map/yudixie_resnet18_translation_rotation_0_240719.json
  brainscore_vision/models/yudixie_resnet18_240719_5/setup.py
  brainscore_vision/models/yudixie_resnet18_240719_5/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1076 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet18_240719_7/__init__.py
  brainscore_vision/models/yudixie_resnet18_240719_7/model.py
  brainscore_vision/models/yudixie_resnet18_240719_7/region_layer_map/yudixie_resnet18_category_class_0_240719.json
  brainscore_vision/models/yudixie_resnet18_240719_7/setup.py
  brainscore_vision/models/yudixie_resnet18_240719_7/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1080 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet18_240719_11/__init__.py
  brainscore_vision/models/yudixie_resnet18_240719_11/model.py
  brainscore_vision/models/yudixie_resnet18_240719_11/region_layer_map/yudixie_resnet18_random_0_240719.json
  brainscore_vision/models/yudixie_resnet18_240719_11/setup.py
  brainscore_vision/models/yudixie_resnet18_240719_11/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1078 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet18_240719_9/__init__.py
  brainscore_vision/models/yudixie_resnet18_240719_9/model.py
  brainscore_vision/models/yudixie_resnet18_240719_9/region_layer_map/yudixie_resnet18_cat_obj_class_all_latents_0_240719.json
  brainscore_vision/models/yudixie_resnet18_240719_9/setup.py
  brainscore_vision/models/yudixie_resnet18_240719_9/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1077 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet18_240719_8/__init__.py
  brainscore_vision/models/yudixie_resnet18_240719_8/model.py
  brainscore_vision/models/yudixie_resnet18_240719_8/region_layer_map/yudixie_resnet18_object_class_0_240719.json
  brainscore_vision/models/yudixie_resnet18_240719_8/setup.py
  brainscore_vision/models/yudixie_resnet18_240719_8/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1075 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet18_240719_6/__init__.py
  brainscore_vision/models/yudixie_resnet18_240719_6/model.py
  brainscore_vision/models/yudixie_resnet18_240719_6/region_layer_map/yudixie_resnet18_distance_translation_rotation_0_240719.json
  brainscore_vision/models/yudixie_resnet18_240719_6/setup.py
  brainscore_vision/models/yudixie_resnet18_240719_6/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1471 Layer Mapping Orchestrator (build:167)
  brainscore_vision/models/yudixie_resnet18_240719_0/region_layer_map/yudixie_resnet18_distance_reg_0_240719.json
  brainscore_vision/models/yudixie_resnet18_240719_1/region_layer_map/yudixie_resnet18_translation_reg_0_240719.json
  brainscore_vision/models/yudixie_resnet18_240719_10/region_layer_map/yudixie_resnet18_imagenet1kpret_0_240719.json
  brainscore_vision/models/yudixie_resnet18_240719_2/region_layer_map/yudixie_resnet18_rotation_reg_0_240719.json
  brainscore_vision/models/yudixie_resnet50_imagenet1kpret_0_240312/region_layer_map/yudixie_resnet50_imagenet1kpret_0_240312.json
Labels: automerge-web, automerge-approved, mapping-complete

#1482 add blt vs model
  brainscore_vision/models/blt-vs/__init__.py
  brainscore_vision/models/blt-vs/model.py
  brainscore_vision/models/blt-vs/pretrained.py
  brainscore_vision/models/blt-vs/setup.py
  brainscore_vision/models/blt-vs/test.py
Labels: trigger-mapping

#1485 Layer Mapping Orchestrator (build:197)
  brainscore_vision/models/blt-vs/region_layer_map/blt_vs.json
Labels: automerge-approved, mapping-complete

#1512 brain-score.org submission (user:542) | (public:False)
  brainscore_vision/models/resnet18_random/__init__.py
  brainscore_vision/models/resnet18_random/archive_name.zip
  brainscore_vision/models/resnet18_random/model.py
  brainscore_vision/models/resnet18_random/requirements.txt
  brainscore_vision/models/resnet18_random/test.py
Labels: automerge-web, automerge-approved, mapping-complete
