Repository brain-score/vision, pull requests merged in 2024-03, with the labels that each got.

#587 brain-score.org (user:386) | Add new plugin(s): models: [eBarlow_Vanilla] | (public:False)
  brainscore_vision/models/eBarlow_Vanilla/__init__.py
  brainscore_vision/models/eBarlow_Vanilla/model.py
  brainscore_vision/models/eBarlow_Vanilla/setup.py
  brainscore_vision/models/eBarlow_Vanilla/test.py
Labels: automerge-web, automerge-approved

#588 brain-score.org (user:386) | Add new plugin(s): models: [eBarlow_lmda_01] | (public:False)
  brainscore_vision/models/eBarlow_lmda_01/__init__.py
  brainscore_vision/models/eBarlow_lmda_01/model.py
  brainscore_vision/models/eBarlow_lmda_01/setup.py
  brainscore_vision/models/eBarlow_lmda_01/test.py
Labels: automerge-web, automerge-approved

#589 brain-score.org (user:514) | Add new plugin(s): models: [cornet_s_0_0_0] | (public:False)
  brainscore_vision/models/cornet_s_0_0_0/__init__.py
  brainscore_vision/models/cornet_s_0_0_0/model.py
  brainscore_vision/models/cornet_s_0_0_0/setup.py
  brainscore_vision/models/cornet_s_0_0_0/test.py
Labels: automerge-web, automerge-approved

#590 brain-score.org (user:490) | Add new plugin(s): models: [unet_ethan] | (public:False)
  brainscore_vision/models/unet_ethan/__init__.py
  brainscore_vision/models/unet_ethan/model.py
  brainscore_vision/models/unet_ethan/setup.py
  brainscore_vision/models/unet_ethan/test.py
Labels: automerge-web, automerge-approved

#592 Transfer plugin information by artifact for scoring runs
  .github/workflows/score_new_plugins.yml
Labels: bug

#621 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/cornet_s_0_2_0/__init__.py
  brainscore_vision/models/cornet_s_0_2_0/model.py
  brainscore_vision/models/cornet_s_0_2_0/setup.py
  brainscore_vision/models/cornet_s_0_2_0/test.py
  brainscore_vision/models/cornet_s_0_3_0/__init__.py
  brainscore_vision/models/cornet_s_0_3_0/model.py
  brainscore_vision/models/cornet_s_0_3_0/setup.py
  brainscore_vision/models/cornet_s_0_3_0/test.py
  brainscore_vision/models/cornet_s_0_4_0/__init__.py
  brainscore_vision/models/cornet_s_0_4_0/model.py
  brainscore_vision/models/cornet_s_0_4_0/setup.py
  brainscore_vision/models/cornet_s_0_4_0/test.py
  brainscore_vision/models/cornet_s_0_5_0/__init__.py
  brainscore_vision/models/cornet_s_0_5_0/model.py
  brainscore_vision/models/cornet_s_0_5_0/setup.py
  brainscore_vision/models/cornet_s_0_5_0/test.py
Labels: automerge-web

#623 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eMMCR_lmda_01V2/__init__.py
  brainscore_vision/models/eMMCR_lmda_01V2/model.py
  brainscore_vision/models/eMMCR_lmda_01V2/setup.py
  brainscore_vision/models/eMMCR_lmda_01V2/test.py
Labels: automerge-web

#640 brain-score.org submission (user:121) | (public:False)
  brainscore_vision/models/yudixie_resnet50_imagenet1kpret_0_240312/__init__.py
  brainscore_vision/models/yudixie_resnet50_imagenet1kpret_0_240312/model.py
  brainscore_vision/models/yudixie_resnet50_imagenet1kpret_0_240312/setup.py
  brainscore_vision/models/yudixie_resnet50_imagenet1kpret_0_240312/test.py
Labels: automerge-web

#644 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eMMCR_VanillaV2/__init__.py
  brainscore_vision/models/eMMCR_VanillaV2/model.py
  brainscore_vision/models/eMMCR_VanillaV2/setup.py
  brainscore_vision/models/eMMCR_VanillaV2/test.py
Labels: automerge-web

#515 brain-score.org (user:424) | Add new plugin(s): models: [vit]
  brainscore_vision/models/vit/__init__.py
  brainscore_vision/models/vit/model.py
  brainscore_vision/models/vit/setup.py
  brainscore_vision/models/vit/test.py
Labels: automerge-web, automerge-approved

#573 brain-score.org (user:386) | Add new plugin(s): models: [resnet50_eMMCR_VanillaV2] | (public:False)
  brainscore_vision/models/resnet50_eMMCR_VanillaV2/model.py
Labels: automerge-web, automerge-approved

#607 brain-score.org (user:386) | Add new plugin(s): models: [eMMCR_Vanilla] | (public:False)
  brainscore_vision/models/eMMCR_Vanilla/__init__.py
  brainscore_vision/models/eMMCR_Vanilla/model.py
  brainscore_vision/models/eMMCR_Vanilla/setup.py
  brainscore_vision/models/eMMCR_Vanilla/test.py
Labels: automerge-web, automerge-approved

#626 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/cornet_s_0_10_0/__init__.py
  brainscore_vision/models/cornet_s_0_10_0/model.py
  brainscore_vision/models/cornet_s_0_10_0/setup.py
  brainscore_vision/models/cornet_s_0_10_0/test.py
  brainscore_vision/models/cornet_s_0_6_0/__init__.py
  brainscore_vision/models/cornet_s_0_6_0/model.py
  brainscore_vision/models/cornet_s_0_6_0/setup.py
  brainscore_vision/models/cornet_s_0_6_0/test.py
  brainscore_vision/models/cornet_s_0_7_0/__init__.py
  brainscore_vision/models/cornet_s_0_7_0/model.py
  brainscore_vision/models/cornet_s_0_7_0/setup.py
  brainscore_vision/models/cornet_s_0_7_0/test.py
  brainscore_vision/models/cornet_s_0_8_0/__init__.py
  brainscore_vision/models/cornet_s_0_8_0/model.py
  brainscore_vision/models/cornet_s_0_8_0/setup.py
  brainscore_vision/models/cornet_s_0_8_0/test.py
  brainscore_vision/models/cornet_s_0_9_0/__init__.py
  brainscore_vision/models/cornet_s_0_9_0/model.py
  brainscore_vision/models/cornet_s_0_9_0/setup.py
  brainscore_vision/models/cornet_s_0_9_0/test.py
Labels: automerge-web, automerge-approved

#628 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/cornet_s_0_11_0/__init__.py
  brainscore_vision/models/cornet_s_0_11_0/model.py
  brainscore_vision/models/cornet_s_0_11_0/setup.py
  brainscore_vision/models/cornet_s_0_11_0/test.py
  brainscore_vision/models/cornet_s_0_12_0/__init__.py
  brainscore_vision/models/cornet_s_0_12_0/model.py
  brainscore_vision/models/cornet_s_0_12_0/setup.py
  brainscore_vision/models/cornet_s_0_12_0/test.py
  brainscore_vision/models/cornet_s_0_13_0/__init__.py
  brainscore_vision/models/cornet_s_0_13_0/model.py
  brainscore_vision/models/cornet_s_0_13_0/setup.py
  brainscore_vision/models/cornet_s_0_13_0/test.py
  brainscore_vision/models/cornet_s_0_14_0/__init__.py
  brainscore_vision/models/cornet_s_0_14_0/model.py
  brainscore_vision/models/cornet_s_0_14_0/setup.py
  brainscore_vision/models/cornet_s_0_14_0/test.py
  brainscore_vision/models/cornet_s_0_15_0/__init__.py
  brainscore_vision/models/cornet_s_0_15_0/model.py
  brainscore_vision/models/cornet_s_0_15_0/setup.py
  brainscore_vision/models/cornet_s_0_15_0/test.py
Labels: automerge-web, automerge-approved

#629 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/cornet_s_1_0_0/__init__.py
  brainscore_vision/models/cornet_s_1_0_0/model.py
  brainscore_vision/models/cornet_s_1_0_0/setup.py
  brainscore_vision/models/cornet_s_1_0_0/test.py
  brainscore_vision/models/cornet_s_1_1_0/__init__.py
  brainscore_vision/models/cornet_s_1_1_0/model.py
  brainscore_vision/models/cornet_s_1_1_0/setup.py
  brainscore_vision/models/cornet_s_1_1_0/test.py
  brainscore_vision/models/cornet_s_1_2_0/__init__.py
  brainscore_vision/models/cornet_s_1_2_0/model.py
  brainscore_vision/models/cornet_s_1_2_0/setup.py
  brainscore_vision/models/cornet_s_1_2_0/test.py
  brainscore_vision/models/cornet_s_1_3_0/__init__.py
  brainscore_vision/models/cornet_s_1_3_0/model.py
  brainscore_vision/models/cornet_s_1_3_0/setup.py
  brainscore_vision/models/cornet_s_1_3_0/test.py
  brainscore_vision/models/cornet_s_1_4_0/__init__.py
  brainscore_vision/models/cornet_s_1_4_0/model.py
  brainscore_vision/models/cornet_s_1_4_0/setup.py
  brainscore_vision/models/cornet_s_1_4_0/test.py
  brainscore_vision/models/cornet_s_1_5_0/__init__.py
  brainscore_vision/models/cornet_s_1_5_0/model.py
  brainscore_vision/models/cornet_s_1_5_0/setup.py
  brainscore_vision/models/cornet_s_1_5_0/test.py
Labels: automerge-web, automerge-approved

#630 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/cornet_s_1_10_0/__init__.py
  brainscore_vision/models/cornet_s_1_10_0/model.py
  brainscore_vision/models/cornet_s_1_10_0/setup.py
  brainscore_vision/models/cornet_s_1_10_0/test.py
  brainscore_vision/models/cornet_s_1_6_0/__init__.py
  brainscore_vision/models/cornet_s_1_6_0/model.py
  brainscore_vision/models/cornet_s_1_6_0/setup.py
  brainscore_vision/models/cornet_s_1_6_0/test.py
  brainscore_vision/models/cornet_s_1_7_0/__init__.py
  brainscore_vision/models/cornet_s_1_7_0/model.py
  brainscore_vision/models/cornet_s_1_7_0/setup.py
  brainscore_vision/models/cornet_s_1_7_0/test.py
  brainscore_vision/models/cornet_s_1_8_0/__init__.py
  brainscore_vision/models/cornet_s_1_8_0/model.py
  brainscore_vision/models/cornet_s_1_8_0/setup.py
  brainscore_vision/models/cornet_s_1_8_0/test.py
  brainscore_vision/models/cornet_s_1_9_0/__init__.py
  brainscore_vision/models/cornet_s_1_9_0/model.py
  brainscore_vision/models/cornet_s_1_9_0/setup.py
  brainscore_vision/models/cornet_s_1_9_0/test.py
Labels: automerge-web, automerge-approved

#631 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/cornet_s_1_11_0/__init__.py
  brainscore_vision/models/cornet_s_1_11_0/model.py
  brainscore_vision/models/cornet_s_1_11_0/setup.py
  brainscore_vision/models/cornet_s_1_11_0/test.py
  brainscore_vision/models/cornet_s_1_12_0/__init__.py
  brainscore_vision/models/cornet_s_1_12_0/model.py
  brainscore_vision/models/cornet_s_1_12_0/setup.py
  brainscore_vision/models/cornet_s_1_12_0/test.py
  brainscore_vision/models/cornet_s_1_13_0/__init__.py
  brainscore_vision/models/cornet_s_1_13_0/model.py
  brainscore_vision/models/cornet_s_1_13_0/setup.py
  brainscore_vision/models/cornet_s_1_13_0/test.py
  brainscore_vision/models/cornet_s_1_14_0/__init__.py
  brainscore_vision/models/cornet_s_1_14_0/model.py
  brainscore_vision/models/cornet_s_1_14_0/setup.py
  brainscore_vision/models/cornet_s_1_14_0/test.py
  brainscore_vision/models/cornet_s_1_15_0/__init__.py
  brainscore_vision/models/cornet_s_1_15_0/model.py
  brainscore_vision/models/cornet_s_1_15_0/setup.py
  brainscore_vision/models/cornet_s_1_15_0/test.py
Labels: automerge-web, automerge-approved

#632 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/cornet_s_2_0_0/__init__.py
  brainscore_vision/models/cornet_s_2_0_0/model.py
  brainscore_vision/models/cornet_s_2_0_0/setup.py
  brainscore_vision/models/cornet_s_2_0_0/test.py
  brainscore_vision/models/cornet_s_2_1_0/__init__.py
  brainscore_vision/models/cornet_s_2_1_0/model.py
  brainscore_vision/models/cornet_s_2_1_0/setup.py
  brainscore_vision/models/cornet_s_2_1_0/test.py
  brainscore_vision/models/cornet_s_2_2_0/__init__.py
  brainscore_vision/models/cornet_s_2_2_0/model.py
  brainscore_vision/models/cornet_s_2_2_0/setup.py
  brainscore_vision/models/cornet_s_2_2_0/test.py
  brainscore_vision/models/cornet_s_2_3_0/__init__.py
  brainscore_vision/models/cornet_s_2_3_0/model.py
  brainscore_vision/models/cornet_s_2_3_0/setup.py
  brainscore_vision/models/cornet_s_2_3_0/test.py
  brainscore_vision/models/cornet_s_2_4_0/__init__.py
  brainscore_vision/models/cornet_s_2_4_0/model.py
  brainscore_vision/models/cornet_s_2_4_0/setup.py
  brainscore_vision/models/cornet_s_2_4_0/test.py
  brainscore_vision/models/cornet_s_2_5_0/__init__.py
  brainscore_vision/models/cornet_s_2_5_0/model.py
  brainscore_vision/models/cornet_s_2_5_0/setup.py
  brainscore_vision/models/cornet_s_2_5_0/test.py
Labels: automerge-web, automerge-approved

#633 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/cornet_s_2_10_0/__init__.py
  brainscore_vision/models/cornet_s_2_10_0/model.py
  brainscore_vision/models/cornet_s_2_10_0/setup.py
  brainscore_vision/models/cornet_s_2_10_0/test.py
  brainscore_vision/models/cornet_s_2_6_0/__init__.py
  brainscore_vision/models/cornet_s_2_6_0/model.py
  brainscore_vision/models/cornet_s_2_6_0/setup.py
  brainscore_vision/models/cornet_s_2_6_0/test.py
  brainscore_vision/models/cornet_s_2_7_0/__init__.py
  brainscore_vision/models/cornet_s_2_7_0/model.py
  brainscore_vision/models/cornet_s_2_7_0/setup.py
  brainscore_vision/models/cornet_s_2_7_0/test.py
  brainscore_vision/models/cornet_s_2_8_0/__init__.py
  brainscore_vision/models/cornet_s_2_8_0/model.py
  brainscore_vision/models/cornet_s_2_8_0/setup.py
  brainscore_vision/models/cornet_s_2_8_0/test.py
  brainscore_vision/models/cornet_s_2_9_0/__init__.py
  brainscore_vision/models/cornet_s_2_9_0/model.py
  brainscore_vision/models/cornet_s_2_9_0/setup.py
  brainscore_vision/models/cornet_s_2_9_0/test.py
Labels: automerge-web, automerge-approved

#634 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/cornet_s_2_11_0/__init__.py
  brainscore_vision/models/cornet_s_2_11_0/model.py
  brainscore_vision/models/cornet_s_2_11_0/setup.py
  brainscore_vision/models/cornet_s_2_11_0/test.py
  brainscore_vision/models/cornet_s_2_12_0/__init__.py
  brainscore_vision/models/cornet_s_2_12_0/model.py
  brainscore_vision/models/cornet_s_2_12_0/setup.py
  brainscore_vision/models/cornet_s_2_12_0/test.py
  brainscore_vision/models/cornet_s_2_13_0/__init__.py
  brainscore_vision/models/cornet_s_2_13_0/model.py
  brainscore_vision/models/cornet_s_2_13_0/setup.py
  brainscore_vision/models/cornet_s_2_13_0/test.py
  brainscore_vision/models/cornet_s_2_14_0/__init__.py
  brainscore_vision/models/cornet_s_2_14_0/model.py
  brainscore_vision/models/cornet_s_2_14_0/setup.py
  brainscore_vision/models/cornet_s_2_14_0/test.py
  brainscore_vision/models/cornet_s_2_15_0/__init__.py
  brainscore_vision/models/cornet_s_2_15_0/model.py
  brainscore_vision/models/cornet_s_2_15_0/setup.py
  brainscore_vision/models/cornet_s_2_15_0/test.py
Labels: automerge-web, automerge-approved

#635 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/cornet_s_3_0_0/__init__.py
  brainscore_vision/models/cornet_s_3_0_0/model.py
  brainscore_vision/models/cornet_s_3_0_0/setup.py
  brainscore_vision/models/cornet_s_3_0_0/test.py
  brainscore_vision/models/cornet_s_3_1_0/__init__.py
  brainscore_vision/models/cornet_s_3_1_0/model.py
  brainscore_vision/models/cornet_s_3_1_0/setup.py
  brainscore_vision/models/cornet_s_3_1_0/test.py
  brainscore_vision/models/cornet_s_3_2_0/__init__.py
  brainscore_vision/models/cornet_s_3_2_0/model.py
  brainscore_vision/models/cornet_s_3_2_0/setup.py
  brainscore_vision/models/cornet_s_3_2_0/test.py
  brainscore_vision/models/cornet_s_3_3_0/__init__.py
  brainscore_vision/models/cornet_s_3_3_0/model.py
  brainscore_vision/models/cornet_s_3_3_0/setup.py
  brainscore_vision/models/cornet_s_3_3_0/test.py
  brainscore_vision/models/cornet_s_3_4_0/__init__.py
  brainscore_vision/models/cornet_s_3_4_0/model.py
  brainscore_vision/models/cornet_s_3_4_0/setup.py
  brainscore_vision/models/cornet_s_3_4_0/test.py
  brainscore_vision/models/cornet_s_3_5_0/__init__.py
  brainscore_vision/models/cornet_s_3_5_0/model.py
  brainscore_vision/models/cornet_s_3_5_0/setup.py
  brainscore_vision/models/cornet_s_3_5_0/test.py
Labels: automerge-web, automerge-approved

#690 add conditionals to automerge action
  .github/workflows/automerge_plugin-only_prs.yml
Labels: bug

#694 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eBarlow_lmda_01_2/__init__.py
  brainscore_vision/models/eBarlow_lmda_01_2/model.py
  brainscore_vision/models/eBarlow_lmda_01_2/setup.py
  brainscore_vision/models/eBarlow_lmda_01_2/test.py
Labels: automerge-web, automerge-approved

#710 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eMMCR_lmda_01_1/__init__.py
  brainscore_vision/models/eMMCR_lmda_01_1/model.py
  brainscore_vision/models/eMMCR_lmda_01_1/setup.py
  brainscore_vision/models/eMMCR_lmda_01_1/test.py
Labels: automerge-web, automerge-approved

#708 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eSimCLR_lmda_01_1/__init__.py
  brainscore_vision/models/eSimCLR_lmda_01_1/model.py
  brainscore_vision/models/eSimCLR_lmda_01_1/setup.py
  brainscore_vision/models/eSimCLR_lmda_01_1/test.py
Labels: automerge-web, automerge-approved

#709 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eMMCR_Vanilla_1/__init__.py
  brainscore_vision/models/eMMCR_Vanilla_1/model.py
  brainscore_vision/models/eMMCR_Vanilla_1/setup.py
  brainscore_vision/models/eMMCR_Vanilla_1/test.py
Labels: automerge-web, automerge-approved

#707 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eSimCLR_Vanilla_2/__init__.py
  brainscore_vision/models/eSimCLR_Vanilla_2/model.py
  brainscore_vision/models/eSimCLR_Vanilla_2/setup.py
  brainscore_vision/models/eSimCLR_Vanilla_2/test.py
Labels: automerge-web, automerge-approved

#705 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eBarlow_Vanilla_1/__init__.py
  brainscore_vision/models/eBarlow_Vanilla_1/model.py
  brainscore_vision/models/eBarlow_Vanilla_1/setup.py
  brainscore_vision/models/eBarlow_Vanilla_1/test.py
Labels: automerge-web, automerge-approved

#704 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eSimCLR_Vanilla_1/__init__.py
  brainscore_vision/models/eSimCLR_Vanilla_1/model.py
  brainscore_vision/models/eSimCLR_Vanilla_1/setup.py
  brainscore_vision/models/eSimCLR_Vanilla_1/test.py
Labels: automerge-web, automerge-approved

#706 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eBarlow_lmda_01_1/__init__.py
  brainscore_vision/models/eBarlow_lmda_01_1/model.py
  brainscore_vision/models/eBarlow_lmda_01_1/setup.py
  brainscore_vision/models/eBarlow_lmda_01_1/test.py
Labels: automerge-web, automerge-approved

#703 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eMMCR_Vanilla_2/__init__.py
  brainscore_vision/models/eMMCR_Vanilla_2/model.py
  brainscore_vision/models/eMMCR_Vanilla_2/setup.py
  brainscore_vision/models/eMMCR_Vanilla_2/test.py
Labels: automerge-web, automerge-approved

#701 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eSimCLR_lmda_01_2/__init__.py
  brainscore_vision/models/eSimCLR_lmda_01_2/model.py
  brainscore_vision/models/eSimCLR_lmda_01_2/setup.py
  brainscore_vision/models/eSimCLR_lmda_01_2/test.py
Labels: automerge-web, automerge-approved

#699 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eBarlow_Vanilla_2/__init__.py
  brainscore_vision/models/eBarlow_Vanilla_2/model.py
  brainscore_vision/models/eBarlow_Vanilla_2/setup.py
  brainscore_vision/models/eBarlow_Vanilla_2/test.py
Labels: automerge-web, automerge-approved

#636 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/cornet_s_3_10_0/__init__.py
  brainscore_vision/models/cornet_s_3_10_0/model.py
  brainscore_vision/models/cornet_s_3_10_0/setup.py
  brainscore_vision/models/cornet_s_3_10_0/test.py
  brainscore_vision/models/cornet_s_3_6_0/__init__.py
  brainscore_vision/models/cornet_s_3_6_0/model.py
  brainscore_vision/models/cornet_s_3_6_0/setup.py
  brainscore_vision/models/cornet_s_3_6_0/test.py
  brainscore_vision/models/cornet_s_3_7_0/__init__.py
  brainscore_vision/models/cornet_s_3_7_0/model.py
  brainscore_vision/models/cornet_s_3_7_0/setup.py
  brainscore_vision/models/cornet_s_3_7_0/test.py
  brainscore_vision/models/cornet_s_3_8_0/__init__.py
  brainscore_vision/models/cornet_s_3_8_0/model.py
  brainscore_vision/models/cornet_s_3_8_0/setup.py
  brainscore_vision/models/cornet_s_3_8_0/test.py
  brainscore_vision/models/cornet_s_3_9_0/__init__.py
  brainscore_vision/models/cornet_s_3_9_0/model.py
  brainscore_vision/models/cornet_s_3_9_0/setup.py
  brainscore_vision/models/cornet_s_3_9_0/test.py
Labels: automerge-web, automerge-approved

#713 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eMMCR_lmda_01_2/__init__.py
  brainscore_vision/models/eMMCR_lmda_01_2/model.py
  brainscore_vision/models/eMMCR_lmda_01_2/setup.py
  brainscore_vision/models/eMMCR_lmda_01_2/test.py
Labels: automerge-web, automerge-approved

#716 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/eMMCR_lmda_01_3/__init__.py
  brainscore_vision/models/eMMCR_lmda_01_3/model.py
  brainscore_vision/models/eMMCR_lmda_01_3/setup.py
  brainscore_vision/models/eMMCR_lmda_01_3/test.py
Labels: automerge-web, automerge-approved
