Repository brain-score/vision, pull requests merged in 2024-10, with the labels that each got.

#1293 brain-score.org submission (user:486) | (public:False)
  brainscore_vision/models/sam_test_resnet/__init__.py
  brainscore_vision/models/sam_test_resnet/model.py
  brainscore_vision/models/sam_test_resnet/requirements.txt
  brainscore_vision/models/sam_test_resnet/test.py
Labels: automerge-web

#1300 brain-score.org submission (user:582) | (public:False)
  brainscore_vision/models/alexnet_7be5be79/setup.py
Labels: automerge-web, automerge-approved

#1301 brain-score.org submission (user:582) | (public:False)
  brainscore_vision/models/alexnet_random/__init__.py
  brainscore_vision/models/alexnet_random/model.py
  brainscore_vision/models/alexnet_random/setup.py
  brainscore_vision/models/alexnet_random/test.py
Labels: automerge-web, automerge-approved

#1309 brain-score.org submission (user:486) | (public:False)
  brainscore_vision/models/sam_test_resnet_3/__init__.py
  brainscore_vision/models/sam_test_resnet_3/model.py
  brainscore_vision/models/sam_test_resnet_3/requirements.txt
  brainscore_vision/models/sam_test_resnet_3/test.py
Labels: automerge-web, automerge-approved

#1313 brain-score.org submission (user:486) | (public:False)
  brainscore_vision/models/sam_test_resnet_4/__init__.py
  brainscore_vision/models/sam_test_resnet_4/model.py
  brainscore_vision/models/sam_test_resnet_4/requirements.txt
  brainscore_vision/models/sam_test_resnet_4/test.py
Labels: automerge-web, automerge-approved

#1339 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/mvimgnet_rf/__init__.py
  brainscore_vision/models/mvimgnet_rf/model.py
  brainscore_vision/models/mvimgnet_rf/setup.py
  brainscore_vision/models/mvimgnet_rf/test.py
Labels: automerge-web, automerge-approved

#1340 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/mvimgnet_ss_00/__init__.py
  brainscore_vision/models/mvimgnet_ss_00/model.py
  brainscore_vision/models/mvimgnet_ss_00/setup.py
  brainscore_vision/models/mvimgnet_ss_00/test.py
Labels: automerge-web, automerge-approved

#1342 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/mvimgnet_ss_03/__init__.py
  brainscore_vision/models/mvimgnet_ss_03/model.py
  brainscore_vision/models/mvimgnet_ss_03/setup.py
  brainscore_vision/models/mvimgnet_ss_03/test.py
Labels: automerge-web, automerge-approved

#1343 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/mvimgnet_ss_05/__init__.py
  brainscore_vision/models/mvimgnet_ss_05/model.py
  brainscore_vision/models/mvimgnet_ss_05/setup.py
  brainscore_vision/models/mvimgnet_ss_05/test.py
Labels: automerge-web, automerge-approved

#1346 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/mvimgnet_ms_05/__init__.py
  brainscore_vision/models/mvimgnet_ms_05/model.py
  brainscore_vision/models/mvimgnet_ms_05/setup.py
  brainscore_vision/models/mvimgnet_ms_05/test.py
Labels: automerge-web, automerge-approved

#1347 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/mvimgnet_ss_02/__init__.py
  brainscore_vision/models/mvimgnet_ss_02/model.py
  brainscore_vision/models/mvimgnet_ss_02/setup.py
  brainscore_vision/models/mvimgnet_ss_02/test.py
Labels: automerge-web, automerge-approved

#1348 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/mvimgnet_ss_04/__init__.py
  brainscore_vision/models/mvimgnet_ss_04/model.py
  brainscore_vision/models/mvimgnet_ss_04/setup.py
  brainscore_vision/models/mvimgnet_ss_04/test.py
Labels: automerge-web, automerge-approved

#1386 brain-score.org submission (user:514) | (public:False)
  brainscore_vision/models/vitb14_dinov2_imagenet1k/__init__.py
  brainscore_vision/models/vitb14_dinov2_imagenet1k/model.py
  brainscore_vision/models/vitb14_dinov2_imagenet1k/setup.py
  brainscore_vision/models/vitb14_dinov2_imagenet1k/test.py
Labels: automerge-web, automerge-approved

#1401 Sync master into develop. Triggered by PR
  brainscore_vision/model_helpers/brain_transformation/__init__.py
Labels: OOM
