Repository brain-score/vision, pull requests merged in 2025-06, with the labels that each got.

#1939 First Pass at Metadata Tagging System Refactor
  brainscore_vision/plugin_management/__init__.py
  brainscore_vision/plugin_management/vision_domain_plugin.py
  pyproject.toml
  tests/test_plugin_management/test_vision_domain_plugin.py
Labels: minor update

#1960 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/p2_evresnet_50_457_0/__init__.py
  brainscore_vision/models/p2_evresnet_50_457_0/evnet/backends.py
  brainscore_vision/models/p2_evresnet_50_457_0/evnet/evnet.py
  brainscore_vision/models/p2_evresnet_50_457_0/evnet/modules.py
  brainscore_vision/models/p2_evresnet_50_457_0/evnet/params.py
  brainscore_vision/models/p2_evresnet_50_457_0/evnet/utils.py
  brainscore_vision/models/p2_evresnet_50_457_0/model.py
  brainscore_vision/models/p2_evresnet_50_457_0/requirements.txt
  brainscore_vision/models/p2_evresnet_50_457_0/test.py
Labels: automerge-web, automerge-approved, trigger-mapping, mapping-complete

#1963 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/p1_evresnet_50_457_1/__init__.py
  brainscore_vision/models/p1_evresnet_50_457_1/evnet/backends.py
  brainscore_vision/models/p1_evresnet_50_457_1/evnet/evnet.py
  brainscore_vision/models/p1_evresnet_50_457_1/evnet/modules.py
  brainscore_vision/models/p1_evresnet_50_457_1/evnet/params.py
  brainscore_vision/models/p1_evresnet_50_457_1/evnet/utils.py
  brainscore_vision/models/p1_evresnet_50_457_1/model.py
  brainscore_vision/models/p1_evresnet_50_457_1/requirements.txt
  brainscore_vision/models/p1_evresnet_50_457_1/test.py
Labels: automerge-web, automerge-approved, mapping-complete
