Repository brain-score/vision, pull requests merged in 2025-01, with the labels that each got.

#1652 add evresnet_50_1 to models
  brainscore_vision/models/evresnet_50_1/__init__.py
  brainscore_vision/models/evresnet_50_1/evnet/backends.py
  brainscore_vision/models/evresnet_50_1/evnet/evnet.py
  brainscore_vision/models/evresnet_50_1/evnet/modules.py
  brainscore_vision/models/evresnet_50_1/evnet/params.py
  brainscore_vision/models/evresnet_50_1/evnet/utils.py
  brainscore_vision/models/evresnet_50_1/model.py
  brainscore_vision/models/evresnet_50_1/requirements.txt
  brainscore_vision/models/evresnet_50_1/test.py
Labels: trigger-mapping

#1663 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/sBarlow_lmda_2/__init__.py
  brainscore_vision/models/sBarlow_lmda_2/model.py
  brainscore_vision/models/sBarlow_lmda_2/region_layer_map/sBarlow_lmda_2.json
  brainscore_vision/models/sBarlow_lmda_2/setup.py
  brainscore_vision/models/sBarlow_lmda_2/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1660 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/sBarlow_lmda_0/__init__.py
  brainscore_vision/models/sBarlow_lmda_0/model.py
  brainscore_vision/models/sBarlow_lmda_0/region_layer_map/sBarlow_lmda_0.json
  brainscore_vision/models/sBarlow_lmda_0/setup.py
  brainscore_vision/models/sBarlow_lmda_0/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1661 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/sBarlow_lmda_01/__init__.py
  brainscore_vision/models/sBarlow_lmda_01/model.py
  brainscore_vision/models/sBarlow_lmda_01/region_layer_map/sBarlow_lmda_01.json
  brainscore_vision/models/sBarlow_lmda_01/setup.py
  brainscore_vision/models/sBarlow_lmda_01/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1664 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/sBarlow_lmda_8/__init__.py
  brainscore_vision/models/sBarlow_lmda_8/model.py
  brainscore_vision/models/sBarlow_lmda_8/region_layer_map/sBarlow_lmda_8.json
  brainscore_vision/models/sBarlow_lmda_8/setup.py
  brainscore_vision/models/sBarlow_lmda_8/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1683 brain-score.org submission (user:488) | (public:False)
  brainscore_vision/models/ReAlnet01/__init__.py
  brainscore_vision/models/ReAlnet01/model.py
  brainscore_vision/models/ReAlnet01/region_layer_map/ReAlnet01.json
  brainscore_vision/models/ReAlnet01/requirements.txt
  brainscore_vision/models/ReAlnet01/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1672 added models 51-76 that are ready to be merged
  brainscore_vision/models/AdvProp_efficientnet_b2/__init__.py
  brainscore_vision/models/AdvProp_efficientnet_b2/model.py
  brainscore_vision/models/AdvProp_efficientnet_b2/region_layer_map/AdvProp_efficientnet-b2.json
  brainscore_vision/models/AdvProp_efficientnet_b2/requirements.txt
  brainscore_vision/models/AdvProp_efficientnet_b2/test.py
  brainscore_vision/models/AdvProp_efficientnet_b8/__init__.py
  brainscore_vision/models/AdvProp_efficientnet_b8/model.py
  brainscore_vision/models/AdvProp_efficientnet_b8/region_layer_map/AdvProp_efficientnet-b8.json
  brainscore_vision/models/AdvProp_efficientnet_b8/requirements.txt
  brainscore_vision/models/AdvProp_efficientnet_b8/test.py
  brainscore_vision/models/BiT_S_R101x3/__init__.py
  brainscore_vision/models/BiT_S_R101x3/model.py
  brainscore_vision/models/BiT_S_R101x3/region_layer_map/BiT-S-R101x3.json
  brainscore_vision/models/BiT_S_R101x3/requirements.txt
  brainscore_vision/models/BiT_S_R101x3/test.py
  brainscore_vision/models/BiT_S_R152x2/__init__.py
  brainscore_vision/models/BiT_S_R152x2/model.py
  brainscore_vision/models/BiT_S_R152x2/region_layer_map/BiT-S-R152x2.json
  brainscore_vision/models/BiT_S_R152x2/requirements.txt
  brainscore_vision/models/BiT_S_R152x2/test.py
  brainscore_vision/models/BiT_S_R152x4/__init__.py
  brainscore_vision/models/BiT_S_R152x4/model.py
  brainscore_vision/models/BiT_S_R152x4/region_layer_map/BiT-S-R152x4.json
  brainscore_vision/models/BiT_S_R152x4/requirements.txt
  brainscore_vision/models/BiT_S_R152x4/test.py
  brainscore_vision/models/BiT_S_R50x3/__init__.py
  brainscore_vision/models/BiT_S_R50x3/model.py
  brainscore_vision/models/BiT_S_R50x3/region_layer_map/BiT-S-R50x3.json
  brainscore_vision/models/BiT_S_R50x3/requirements.txt
  brainscore_vision/models/BiT_S_R50x3/test.py
  brainscore_vision/models/convnext_tiny_sup/__init__.py
  brainscore_vision/models/convnext_tiny_sup/model.py
  brainscore_vision/models/convnext_tiny_sup/region_layer_map/convnext_tiny_sup.json
  brainscore_vision/models/convnext_tiny_sup/requirements.txt
  brainscore_vision/models/convnext_tiny_sup/test.py
  brainscore_vision/models/imagenet_l2_3_0/__init__.py
  brainscore_vision/models/imagenet_l2_3_0/model.py
  brainscore_vision/models/imagenet_l2_3_0/region_layer_map/imagenet_l2_3_0.json
  brainscore_vision/models/imagenet_l2_3_0/requirements.txt
  brainscore_vision/models/imagenet_l2_3_0/test.py
  brainscore_vision/models/resnet50_finetune_cutmix_AVGe2e3_robust_linf8255_e0_247x234/__init__.py
  brainscore_vision/models/resnet50_finetune_cutmix_AVGe2e3_robust_linf8255_e0_247x234/model.py
  brainscore_vision/models/resnet50_finetune_cutmix_AVGe2e3_robust_linf8255_e0_247x234/region_layer_map/resnet50_finetune_cutmix_AVGe2e3_robust_linf8255_e0_247x234.json
  brainscore_vision/models/resnet50_finetune_cutmix_AVGe2e3_robust_linf8255_e0_247x234/requirements.txt
  brainscore_vision/models/resnet50_finetune_cutmix_AVGe2e3_robust_linf8255_e0_247x234/test.py
  brainscore_vision/models/resnet50_robust_l2_eps3/__init__.py
  brainscore_vision/models/resnet50_robust_l2_eps3/model.py
  brainscore_vision/models/resnet50_robust_l2_eps3/region_layer_map/resnet50_robust_l2_eps3.json
  brainscore_vision/models/resnet50_robust_l2_eps3/requirements.txt
  brainscore_vision/models/resnet50_robust_l2_eps3/test.py
  brainscore_vision/models/resnet_50_robust/region_layer_map/resnet-50-robust.json
Labels: OOM

#1686 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/voneresnet_50_no_weight/__init__.py
  brainscore_vision/models/voneresnet_50_no_weight/evnet/backends.py
  brainscore_vision/models/voneresnet_50_no_weight/evnet/evnet.py
  brainscore_vision/models/voneresnet_50_no_weight/evnet/modules.py
  brainscore_vision/models/voneresnet_50_no_weight/evnet/params.py
  brainscore_vision/models/voneresnet_50_no_weight/evnet/utils.py
  brainscore_vision/models/voneresnet_50_no_weight/model.py
  brainscore_vision/models/voneresnet_50_no_weight/requirements.txt
  brainscore_vision/models/voneresnet_50_no_weight/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1696 Adding models from timm lib
  brainscore_vision/models/timm_models/__init__.py
  brainscore_vision/models/timm_models/model.py
  brainscore_vision/models/timm_models/model_configs.json
  brainscore_vision/models/timm_models/requirements.txt
  brainscore_vision/models/timm_models/test.py
Labels: trigger-mapping, mapping-complete

#1685 Adds 4 Missing Models
  brainscore_vision/models/efficientnet_b0/__init__.py
  brainscore_vision/models/efficientnet_b0/model.py
  brainscore_vision/models/efficientnet_b0/region_layer_map/efficientnet_b0.json
  brainscore_vision/models/efficientnet_b0/requirements.txt
  brainscore_vision/models/efficientnet_b0/test.py
  brainscore_vision/models/resnet50_VITO_8deg_cc/__init__.py
  brainscore_vision/models/resnet50_VITO_8deg_cc/helpers/resnet.py
  brainscore_vision/models/resnet50_VITO_8deg_cc/helpers/spatialattn.py
  brainscore_vision/models/resnet50_VITO_8deg_cc/model.py
  brainscore_vision/models/resnet50_VITO_8deg_cc/region_layer_map/resnet50-VITO-8deg-cc.json
  brainscore_vision/models/resnet50_VITO_8deg_cc/requirements.txt
  brainscore_vision/models/resnet50_VITO_8deg_cc/test.py
  brainscore_vision/models/resnet50_robust_l2_eps1/__init__.py
  brainscore_vision/models/resnet50_robust_l2_eps1/model.py
  brainscore_vision/models/resnet50_robust_l2_eps1/region_layer_map/resnet50_robust_l2_eps1.json
  brainscore_vision/models/resnet50_robust_l2_eps1/requirements.txt
  brainscore_vision/models/resnet50_robust_l2_eps1/test.py
Labels: mapping-complete

#1704 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/scsBarlow_lmda_1/__init__.py
  brainscore_vision/models/scsBarlow_lmda_1/model.py
  brainscore_vision/models/scsBarlow_lmda_1/region_layer_map/scsBarlow_lmda_1.json
  brainscore_vision/models/scsBarlow_lmda_1/setup.py
  brainscore_vision/models/scsBarlow_lmda_1/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1705 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/scsBarlow_lmda_2/__init__.py
  brainscore_vision/models/scsBarlow_lmda_2/model.py
  brainscore_vision/models/scsBarlow_lmda_2/region_layer_map/scsBarlow_lmda_2.json
  brainscore_vision/models/scsBarlow_lmda_2/setup.py
  brainscore_vision/models/scsBarlow_lmda_2/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1707 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/scsBarlow_lmda_4/__init__.py
  brainscore_vision/models/scsBarlow_lmda_4/model.py
  brainscore_vision/models/scsBarlow_lmda_4/region_layer_map/scsBarlow_lmda_4.json
  brainscore_vision/models/scsBarlow_lmda_4/setup.py
  brainscore_vision/models/scsBarlow_lmda_4/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1700 add models resnet50-SIN, resnet50-SIN_IN, resnet50-SIN_IN_IN
  brainscore_vision/models/resnet50_SIN/__init__.py
  brainscore_vision/models/resnet50_SIN/model.py
  brainscore_vision/models/resnet50_SIN/region_layer_map/resnet50-SIN.json
  brainscore_vision/models/resnet50_SIN/requirements.txt
  brainscore_vision/models/resnet50_SIN/test.py
  brainscore_vision/models/resnet50_SIN_IN/__init__.py
  brainscore_vision/models/resnet50_SIN_IN/model.py
  brainscore_vision/models/resnet50_SIN_IN/region_layer_map/resnet50-SIN_IN.json
  brainscore_vision/models/resnet50_SIN_IN/requirements.txt
  brainscore_vision/models/resnet50_SIN_IN/test.py
  brainscore_vision/models/resnet50_SIN_IN_IN/__init__.py
  brainscore_vision/models/resnet50_SIN_IN_IN/model.py
  brainscore_vision/models/resnet50_SIN_IN_IN/region_layer_map/resnet50-SIN_IN_IN.json
  brainscore_vision/models/resnet50_SIN_IN_IN/requirements.txt
  brainscore_vision/models/resnet50_SIN_IN_IN/test.py
Labels: mapping-complete

#1695 Reconvert indexerror models
  brainscore_vision/models/Res2Net50_26w_4s/__init__.py
  brainscore_vision/models/Res2Net50_26w_4s/helpers/resnet_helpers.py
  brainscore_vision/models/Res2Net50_26w_4s/model.py
  brainscore_vision/models/Res2Net50_26w_4s/region_layer_map/Res2Net50_26w_4s.json
  brainscore_vision/models/Res2Net50_26w_4s/requirements.txt
  brainscore_vision/models/Res2Net50_26w_4s/test.py
  brainscore_vision/models/efficientnet_b7/__init__.py
  brainscore_vision/models/efficientnet_b7/model.py
  brainscore_vision/models/efficientnet_b7/region_layer_map/efficientnet-b7.json
  brainscore_vision/models/efficientnet_b7/requirements.txt
  brainscore_vision/models/efficientnet_b7/test.py
  brainscore_vision/models/resnet_18_test_m/__init__.py
  brainscore_vision/models/resnet_18_test_m/helpers/resnet.py
  brainscore_vision/models/resnet_18_test_m/model.py
  brainscore_vision/models/resnet_18_test_m/region_layer_map/resnet-18_test_m.json
  brainscore_vision/models/resnet_18_test_m/requirements.txt
  brainscore_vision/models/resnet_18_test_m/test.py
  brainscore_vision/models/shufflenet_v2_x1_0/__init__.py
  brainscore_vision/models/shufflenet_v2_x1_0/model.py
  brainscore_vision/models/shufflenet_v2_x1_0/region_layer_map/shufflenet_v2_x1_0.json
  brainscore_vision/models/shufflenet_v2_x1_0/requirements.txt
  brainscore_vision/models/shufflenet_v2_x1_0/test.py
Labels: mapping-complete

#1702 Layer Mapping Orchestrator (build:349)
  brainscore_vision/models/densenet_121/region_layer_map/densenet-121.json
  brainscore_vision/models/densenet_169/region_layer_map/densenet-169.json
  brainscore_vision/models/densenet_201/region_layer_map/densenet-201.json
Labels: mapping-complete

#1719 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/voneresnet_50_1/__init__.py
  brainscore_vision/models/voneresnet_50_1/evnet/backends.py
  brainscore_vision/models/voneresnet_50_1/evnet/evnet.py
  brainscore_vision/models/voneresnet_50_1/evnet/modules.py
  brainscore_vision/models/voneresnet_50_1/evnet/params.py
  brainscore_vision/models/voneresnet_50_1/evnet/utils.py
  brainscore_vision/models/voneresnet_50_1/model.py
  brainscore_vision/models/voneresnet_50_1/requirements.txt
  brainscore_vision/models/voneresnet_50_1/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1715 add models resnet50-barlow, resnet50-vicreg
  brainscore_vision/models/resnet50_barlow/__init__.py
  brainscore_vision/models/resnet50_barlow/model.py
  brainscore_vision/models/resnet50_barlow/region_layer_map/resnet50-barlow.json
  brainscore_vision/models/resnet50_barlow/requirements.txt
  brainscore_vision/models/resnet50_barlow/test.py
  brainscore_vision/models/resnet50_vicreg/__init__.py
  brainscore_vision/models/resnet50_vicreg/model.py
  brainscore_vision/models/resnet50_vicreg/region_layer_map/resnet50-vicreg.json
  brainscore_vision/models/resnet50_vicreg/requirements.txt
  brainscore_vision/models/resnet50_vicreg/test.py
Labels: mapping-complete

#1714 Add 3 more resnet50 variants
  brainscore_vision/models/resnet50_moclr8deg/__init__.py
  brainscore_vision/models/resnet50_moclr8deg/helpers/helpers.py
  brainscore_vision/models/resnet50_moclr8deg/model.py
  brainscore_vision/models/resnet50_moclr8deg/region_layer_map/resnet50-moclr8deg.json
  brainscore_vision/models/resnet50_moclr8deg/requirements.txt
  brainscore_vision/models/resnet50_moclr8deg/test.py
  brainscore_vision/models/resnet50_vitoimagevidnet8/__init__.py
  brainscore_vision/models/resnet50_vitoimagevidnet8/helpers/helpers.py
  brainscore_vision/models/resnet50_vitoimagevidnet8/model.py
  brainscore_vision/models/resnet50_vitoimagevidnet8/region_layer_map/resnet50-vitoimagevidnet8.json
  brainscore_vision/models/resnet50_vitoimagevidnet8/requirements.txt
  brainscore_vision/models/resnet50_vitoimagevidnet8/test.py
Labels: mapping-complete

#1713 add models voneresnet-50-robust, voneresnet-50
  brainscore_vision/models/voneresnet_50/__init__.py
  brainscore_vision/models/voneresnet_50/model.py
  brainscore_vision/models/voneresnet_50/region_layer_map/voneresnet-50.json
  brainscore_vision/models/voneresnet_50/requirements.txt
  brainscore_vision/models/voneresnet_50/test.py
  brainscore_vision/models/voneresnet_50_robust/__init__.py
  brainscore_vision/models/voneresnet_50_robust/model.py
  brainscore_vision/models/voneresnet_50_robust/region_layer_map/voneresnet-50-robust.json
  brainscore_vision/models/voneresnet_50_robust/requirements.txt
  brainscore_vision/models/voneresnet_50_robust/test.py
Labels: mapping-complete

#1697 Submit new models called ReAlnets (ReAlnet01-ReAlnet10, in one directory)
  brainscore_vision/models/ReAlnet/__init__.py
  brainscore_vision/models/ReAlnet/model.py
  brainscore_vision/models/ReAlnet/requirements.txt
  brainscore_vision/models/ReAlnet/test.py
  brainscore_vision/models/ReAlnet/weights.json
  brainscore_vision/models/ReAlnet01/__init__.py
  brainscore_vision/models/ReAlnet01/region_layer_map/ReAlnet01.json
  brainscore_vision/models/ReAlnet01/test.py
Labels: trigger-mapping, mapping-complete

#1733 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet50_250117_4/__init__.py
  brainscore_vision/models/yudixie_resnet50_250117_4/model.py
  brainscore_vision/models/yudixie_resnet50_250117_4/region_layer_map/yudixie_resnet50_distance_rotation_0_240908.json
  brainscore_vision/models/yudixie_resnet50_250117_4/setup.py
  brainscore_vision/models/yudixie_resnet50_250117_4/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1731 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet50_250117_2/__init__.py
  brainscore_vision/models/yudixie_resnet50_250117_2/model.py
  brainscore_vision/models/yudixie_resnet50_250117_2/region_layer_map/yudixie_resnet50_rotation_reg_0_240908.json
  brainscore_vision/models/yudixie_resnet50_250117_2/setup.py
  brainscore_vision/models/yudixie_resnet50_250117_2/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1732 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet50_250117_3/__init__.py
  brainscore_vision/models/yudixie_resnet50_250117_3/model.py
  brainscore_vision/models/yudixie_resnet50_250117_3/region_layer_map/yudixie_resnet50_distance_translation_0_240908.json
  brainscore_vision/models/yudixie_resnet50_250117_3/setup.py
  brainscore_vision/models/yudixie_resnet50_250117_3/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1730 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet50_250117_1/__init__.py
  brainscore_vision/models/yudixie_resnet50_250117_1/model.py
  brainscore_vision/models/yudixie_resnet50_250117_1/region_layer_map/yudixie_resnet50_translation_reg_0_240908.json
  brainscore_vision/models/yudixie_resnet50_250117_1/setup.py
  brainscore_vision/models/yudixie_resnet50_250117_1/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1734 brain-score.org submission (user:413) | (public:False)
  brainscore_vision/models/yudixie_resnet50_250117_5/__init__.py
  brainscore_vision/models/yudixie_resnet50_250117_5/model.py
  brainscore_vision/models/yudixie_resnet50_250117_5/region_layer_map/yudixie_resnet50_translation_rotation_0_240908.json
  brainscore_vision/models/yudixie_resnet50_250117_5/setup.py
  brainscore_vision/models/yudixie_resnet50_250117_5/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1718 add models grcnn, grcnn_109
  brainscore_vision/models/grcnn/__init__.py
  brainscore_vision/models/grcnn/helpers/helpers.py
  brainscore_vision/models/grcnn/model.py
  brainscore_vision/models/grcnn/region_layer_map/grcnn.json
  brainscore_vision/models/grcnn/requirements.txt
  brainscore_vision/models/grcnn/test.py
  brainscore_vision/models/grcnn_109/__init__.py
  brainscore_vision/models/grcnn_109/helpers/helpers.py
  brainscore_vision/models/grcnn_109/model.py
  brainscore_vision/models/grcnn_109/region_layer_map/grcnn_109.json
  brainscore_vision/models/grcnn_109/requirements.txt
  brainscore_vision/models/grcnn_109/test.py
Labels: OOM, Skip, mapping-complete

#1699 add vonegrcnn_62e_nobn model
  brainscore_vision/models/vonegrcnn_62e_nobn/__init__.py
  brainscore_vision/models/vonegrcnn_62e_nobn/helpers/vongrcnn_helpers.py
  brainscore_vision/models/vonegrcnn_62e_nobn/model.py
  brainscore_vision/models/vonegrcnn_62e_nobn/region_layer_map/vonegrcnn_62e_nobn.json
  brainscore_vision/models/vonegrcnn_62e_nobn/requirements.txt
  brainscore_vision/models/vonegrcnn_62e_nobn/test.py
Labels: OOM, mapping-complete

#1737 Add inception_v1
  brainscore_vision/models/inception_v1/__init__.py
  brainscore_vision/models/inception_v1/model.py
  brainscore_vision/models/inception_v1/requirements.txt
  brainscore_vision/models/inception_v1/test.py
Labels: trigger-mapping

#1748 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/voneresnet_50_3/__init__.py
  brainscore_vision/models/voneresnet_50_3/evnet/backends.py
  brainscore_vision/models/voneresnet_50_3/evnet/evnet.py
  brainscore_vision/models/voneresnet_50_3/evnet/modules.py
  brainscore_vision/models/voneresnet_50_3/evnet/params.py
  brainscore_vision/models/voneresnet_50_3/evnet/utils.py
  brainscore_vision/models/voneresnet_50_3/model.py
  brainscore_vision/models/voneresnet_50_3/requirements.txt
  brainscore_vision/models/voneresnet_50_3/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1749 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/evresnet_50_4/__init__.py
  brainscore_vision/models/evresnet_50_4/evnet/backends.py
  brainscore_vision/models/evresnet_50_4/evnet/evnet.py
  brainscore_vision/models/evresnet_50_4/evnet/modules.py
  brainscore_vision/models/evresnet_50_4/evnet/params.py
  brainscore_vision/models/evresnet_50_4/evnet/utils.py
  brainscore_vision/models/evresnet_50_4/model.py
  brainscore_vision/models/evresnet_50_4/requirements.txt
  brainscore_vision/models/evresnet_50_4/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1750 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/resnet_50_2/__init__.py
  brainscore_vision/models/resnet_50_2/evnet/backends.py
  brainscore_vision/models/resnet_50_2/evnet/evnet.py
  brainscore_vision/models/resnet_50_2/evnet/modules.py
  brainscore_vision/models/resnet_50_2/evnet/params.py
  brainscore_vision/models/resnet_50_2/evnet/utils.py
  brainscore_vision/models/resnet_50_2/model.py
  brainscore_vision/models/resnet_50_2/region_layer_map/resnet_50_2.json
  brainscore_vision/models/resnet_50_2/requirements.txt
  brainscore_vision/models/resnet_50_2/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1740 add mobilenet_v2_0_5_192
  brainscore_vision/models/mobilenet_v2_0_5_192/__init__.py
  brainscore_vision/models/mobilenet_v2_0_5_192/model.py
  brainscore_vision/models/mobilenet_v2_0_5_192/region_layer_map/mobilenet_v2_0_5_192.json
  brainscore_vision/models/mobilenet_v2_0_5_192/requirements.txt
  brainscore_vision/models/mobilenet_v2_0_5_192/test.py
Labels: mapping-complete

#1741 add mobilenet_v2_0_5_224
  brainscore_vision/models/mobilenet_v2_0_5_224/__init__.py
  brainscore_vision/models/mobilenet_v2_0_5_224/model.py
  brainscore_vision/models/mobilenet_v2_0_5_224/region_layer_map/mobilenet_v2_0_5_224.json
  brainscore_vision/models/mobilenet_v2_0_5_224/requirements.txt
  brainscore_vision/models/mobilenet_v2_0_5_224/test.py
Labels: mapping-complete

#1743 add mobilenet_v2_0_75_192
  brainscore_vision/models/mobilenet_v2_0_75_192/__init__.py
  brainscore_vision/models/mobilenet_v2_0_75_192/model.py
  brainscore_vision/models/mobilenet_v2_0_75_192/region_layer_map/mobilenet_v2_0_75_192.json
  brainscore_vision/models/mobilenet_v2_0_75_192/requirements.txt
  brainscore_vision/models/mobilenet_v2_0_75_192/test.py
Labels: mapping-complete

#1753 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/evresnet_50_4_no_mapping/__init__.py
  brainscore_vision/models/evresnet_50_4_no_mapping/evnet/backends.py
  brainscore_vision/models/evresnet_50_4_no_mapping/evnet/evnet.py
  brainscore_vision/models/evresnet_50_4_no_mapping/evnet/modules.py
  brainscore_vision/models/evresnet_50_4_no_mapping/evnet/params.py
  brainscore_vision/models/evresnet_50_4_no_mapping/evnet/utils.py
  brainscore_vision/models/evresnet_50_4_no_mapping/model.py
  brainscore_vision/models/evresnet_50_4_no_mapping/region_layer_map/evresnet_50_4_no_mapping.json
  brainscore_vision/models/evresnet_50_4_no_mapping/requirements.txt
  brainscore_vision/models/evresnet_50_4_no_mapping/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1754 add nasnets
  brainscore_vision/models/nasnet_large/__init__.py
  brainscore_vision/models/nasnet_large/model.py
  brainscore_vision/models/nasnet_large/region_layer_map/nasnet_large.json
  brainscore_vision/models/nasnet_large/requirements.txt
  brainscore_vision/models/nasnet_large/test.py
  brainscore_vision/models/nasnet_mobile/__init__.py
  brainscore_vision/models/nasnet_mobile/model.py
  brainscore_vision/models/nasnet_mobile/region_layer_map/nasnet_mobile.json
  brainscore_vision/models/nasnet_mobile/requirements.txt
  brainscore_vision/models/nasnet_mobile/test.py
Labels: OOM, mapping-complete

#1756 add vgg-16 and vgg-19
  brainscore_vision/models/vgg_16/__init__.py
  brainscore_vision/models/vgg_16/model.py
  brainscore_vision/models/vgg_16/region_layer_map/vgg_16.json
  brainscore_vision/models/vgg_16/requirements.txt
  brainscore_vision/models/vgg_16/test.py
  brainscore_vision/models/vgg_19/__init__.py
  brainscore_vision/models/vgg_19/model.py
  brainscore_vision/models/vgg_19/region_layer_map/vgg_19.json
  brainscore_vision/models/vgg_19/requirements.txt
  brainscore_vision/models/vgg_19/test.py
Labels: mapping-complete

#1757 add resnet v1s
  brainscore_vision/models/resnet_101_v1/__init__.py
  brainscore_vision/models/resnet_101_v1/model.py
  brainscore_vision/models/resnet_101_v1/region_layer_map/resnet_101_v1.json
  brainscore_vision/models/resnet_101_v1/requirements.txt
  brainscore_vision/models/resnet_101_v1/test.py
  brainscore_vision/models/resnet_152_v1/__init__.py
  brainscore_vision/models/resnet_152_v1/model.py
  brainscore_vision/models/resnet_152_v1/region_layer_map/resnet_152_v1.json
  brainscore_vision/models/resnet_152_v1/requirements.txt
  brainscore_vision/models/resnet_152_v1/test.py
  brainscore_vision/models/resnet_50_v1/__init__.py
  brainscore_vision/models/resnet_50_v1/model.py
  brainscore_vision/models/resnet_50_v1/region_layer_map/resnet_50_v1.json
  brainscore_vision/models/resnet_50_v1/requirements.txt
  brainscore_vision/models/resnet_50_v1/test.py
Labels: OOM, mapping-complete

#1744 add mobilenet_v2_0_75_224
  brainscore_vision/models/mobilenet_v2_0_75_224/__init__.py
  brainscore_vision/models/mobilenet_v2_0_75_224/model.py
  brainscore_vision/models/mobilenet_v2_0_75_224/region_layer_map/mobilenet_v2_0_75_224.json
  brainscore_vision/models/mobilenet_v2_0_75_224/requirements.txt
  brainscore_vision/models/mobilenet_v2_0_75_224/test.py
Labels: mapping-complete

#1745 add mobilenet_v2_1_0_128
  brainscore_vision/models/mobilenet_v2_1_0_128/__init__.py
  brainscore_vision/models/mobilenet_v2_1_0_128/model.py
  brainscore_vision/models/mobilenet_v2_1_0_128/region_layer_map/mobilenet_v2_1_0_128.json
  brainscore_vision/models/mobilenet_v2_1_0_128/requirements.txt
  brainscore_vision/models/mobilenet_v2_1_0_128/test.py
Labels: mapping-complete

#1746 add mobilenet_v2_1_0_160
  brainscore_vision/models/mobilenet_v2_1_0_160/__init__.py
  brainscore_vision/models/mobilenet_v2_1_0_160/model.py
  brainscore_vision/models/mobilenet_v2_1_0_160/region_layer_map/mobilenet_v2_1_0_160.json
  brainscore_vision/models/mobilenet_v2_1_0_160/requirements.txt
  brainscore_vision/models/mobilenet_v2_1_0_160/test.py
Labels: mapping-complete

#1747 add mobilenet_v2_1_0_192
  brainscore_vision/models/mobilenet_v2_1_0_192/__init__.py
  brainscore_vision/models/mobilenet_v2_1_0_192/model.py
  brainscore_vision/models/mobilenet_v2_1_0_192/region_layer_map/mobilenet_v2_1_0_192.json
  brainscore_vision/models/mobilenet_v2_1_0_192/requirements.txt
  brainscore_vision/models/mobilenet_v2_1_0_192/test.py
Labels: mapping-complete
