Repository brain-score/vision, pull requests merged in 2025-04, with the labels that each got.

#1850 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/evresnet_50_5/__init__.py
  brainscore_vision/models/evresnet_50_5/evnet/backends.py
  brainscore_vision/models/evresnet_50_5/evnet/evnet.py
  brainscore_vision/models/evresnet_50_5/evnet/modules.py
  brainscore_vision/models/evresnet_50_5/evnet/params.py
  brainscore_vision/models/evresnet_50_5/evnet/utils.py
  brainscore_vision/models/evresnet_50_5/model.py
  brainscore_vision/models/evresnet_50_5/requirements.txt
  brainscore_vision/models/evresnet_50_5/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1851 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/evresnet_50_6/__init__.py
  brainscore_vision/models/evresnet_50_6/evnet/backends.py
  brainscore_vision/models/evresnet_50_6/evnet/evnet.py
  brainscore_vision/models/evresnet_50_6/evnet/modules.py
  brainscore_vision/models/evresnet_50_6/evnet/params.py
  brainscore_vision/models/evresnet_50_6/evnet/utils.py
  brainscore_vision/models/evresnet_50_6/model.py
  brainscore_vision/models/evresnet_50_6/requirements.txt
  brainscore_vision/models/evresnet_50_6/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1859 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-Barlow_lmda_05/__init__.py
  brainscore_vision/models/CE-Barlow_lmda_05/model.py
  brainscore_vision/models/CE-Barlow_lmda_05/region_layer_map/CE-Barlow_lmda_05.json
  brainscore_vision/models/CE-Barlow_lmda_05/setup.py
  brainscore_vision/models/CE-Barlow_lmda_05/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1856 adding briaai rmbg model
  brainscore_vision/models/briaai_rmbg_1_4/__init__.py
  brainscore_vision/models/briaai_rmbg_1_4/model.py
  brainscore_vision/models/briaai_rmbg_1_4/region_layer_map/briaai_rmbg_1_4.json
  brainscore_vision/models/briaai_rmbg_1_4/requirements.txt
  brainscore_vision/models/briaai_rmbg_1_4/test.py
Labels: trigger-mapping, mapping-complete

#1855 adding yolos_tiny
  brainscore_vision/models/scc_yolos_tiny/__init__.py
  brainscore_vision/models/scc_yolos_tiny/model.py
  brainscore_vision/models/scc_yolos_tiny/region_layer_map/yolos_tiny.json
  brainscore_vision/models/scc_yolos_tiny/requirements.txt
  brainscore_vision/models/scc_yolos_tiny/test.py
Labels: trigger-mapping, mapping-complete

#1863 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-Barlow_lmda_02/__init__.py
  brainscore_vision/models/CE-Barlow_lmda_02/model.py
  brainscore_vision/models/CE-Barlow_lmda_02/region_layer_map/CE-Barlow_lmda_02.json
  brainscore_vision/models/CE-Barlow_lmda_02/setup.py
  brainscore_vision/models/CE-Barlow_lmda_02/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1861 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-Barlow_lmda_01/__init__.py
  brainscore_vision/models/CE-Barlow_lmda_01/model.py
  brainscore_vision/models/CE-Barlow_lmda_01/region_layer_map/CE-Barlow_lmda_01.json
  brainscore_vision/models/CE-Barlow_lmda_01/setup.py
  brainscore_vision/models/CE-Barlow_lmda_01/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1867 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-MMCR_lmda_0001/__init__.py
  brainscore_vision/models/CE-MMCR_lmda_0001/model.py
  brainscore_vision/models/CE-MMCR_lmda_0001/region_layer_map/CE-MMCR_lmda_0001.json
  brainscore_vision/models/CE-MMCR_lmda_0001/setup.py
  brainscore_vision/models/CE-MMCR_lmda_0001/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1866 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-MMCR_lmda_01/__init__.py
  brainscore_vision/models/CE-MMCR_lmda_01/model.py
  brainscore_vision/models/CE-MMCR_lmda_01/region_layer_map/CE-MMCR_lmda_01.json
  brainscore_vision/models/CE-MMCR_lmda_01/setup.py
  brainscore_vision/models/CE-MMCR_lmda_01/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1862 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-Barlow_lmda_0001/__init__.py
  brainscore_vision/models/CE-Barlow_lmda_0001/model.py
  brainscore_vision/models/CE-Barlow_lmda_0001/region_layer_map/CE-Barlow_lmda_0001.json
  brainscore_vision/models/CE-Barlow_lmda_0001/setup.py
  brainscore_vision/models/CE-Barlow_lmda_0001/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1864 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-Barlow_lmda_03/__init__.py
  brainscore_vision/models/CE-Barlow_lmda_03/model.py
  brainscore_vision/models/CE-Barlow_lmda_03/region_layer_map/CE-Barlow_lmda_03.json
  brainscore_vision/models/CE-Barlow_lmda_03/setup.py
  brainscore_vision/models/CE-Barlow_lmda_03/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1876 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-Barlow_lmda_04/__init__.py
  brainscore_vision/models/CE-Barlow_lmda_04/model.py
  brainscore_vision/models/CE-Barlow_lmda_04/region_layer_map/CE-Barlow_lmda_04.json
  brainscore_vision/models/CE-Barlow_lmda_04/setup.py
  brainscore_vision/models/CE-Barlow_lmda_04/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1880 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-MMCR_lmda_02/__init__.py
  brainscore_vision/models/CE-MMCR_lmda_02/model.py
  brainscore_vision/models/CE-MMCR_lmda_02/region_layer_map/CE-MMCR_lmda_02.json
  brainscore_vision/models/CE-MMCR_lmda_02/setup.py
  brainscore_vision/models/CE-MMCR_lmda_02/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1882 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-MMCR_lmda_00/__init__.py
  brainscore_vision/models/CE-MMCR_lmda_00/model.py
  brainscore_vision/models/CE-MMCR_lmda_00/region_layer_map/CE-MMCR_lmda_00.json
  brainscore_vision/models/CE-MMCR_lmda_00/setup.py
  brainscore_vision/models/CE-MMCR_lmda_00/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1883 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-MMCR_lmda_04/__init__.py
  brainscore_vision/models/CE-MMCR_lmda_04/model.py
  brainscore_vision/models/CE-MMCR_lmda_04/region_layer_map/CE-MMCR_lmda_04.json
  brainscore_vision/models/CE-MMCR_lmda_04/setup.py
  brainscore_vision/models/CE-MMCR_lmda_04/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1885 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-SimCLR_lmda_0/__init__.py
  brainscore_vision/models/CE-SimCLR_lmda_0/model.py
  brainscore_vision/models/CE-SimCLR_lmda_0/region_layer_map/CE-SimCLR_lmda_00.json
  brainscore_vision/models/CE-SimCLR_lmda_0/setup.py
  brainscore_vision/models/CE-SimCLR_lmda_0/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1884 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-MMCR_lmda_05/__init__.py
  brainscore_vision/models/CE-MMCR_lmda_05/model.py
  brainscore_vision/models/CE-MMCR_lmda_05/region_layer_map/CE-MMCR_lmda_05.json
  brainscore_vision/models/CE-MMCR_lmda_05/setup.py
  brainscore_vision/models/CE-MMCR_lmda_05/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1887 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-SimCLR_lmda_01/__init__.py
  brainscore_vision/models/CE-SimCLR_lmda_01/model.py
  brainscore_vision/models/CE-SimCLR_lmda_01/region_layer_map/CE-SimCLR_lmda_01.json
  brainscore_vision/models/CE-SimCLR_lmda_01/setup.py
  brainscore_vision/models/CE-SimCLR_lmda_01/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1886 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-SimCLR_lmda_0001/__init__.py
  brainscore_vision/models/CE-SimCLR_lmda_0001/model.py
  brainscore_vision/models/CE-SimCLR_lmda_0001/region_layer_map/CE-SimCLR_lmda_0001.json
  brainscore_vision/models/CE-SimCLR_lmda_0001/setup.py
  brainscore_vision/models/CE-SimCLR_lmda_0001/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1890 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-SimCLR_lmda_04/__init__.py
  brainscore_vision/models/CE-SimCLR_lmda_04/model.py
  brainscore_vision/models/CE-SimCLR_lmda_04/region_layer_map/CE-SimCLR_lmda_04.json
  brainscore_vision/models/CE-SimCLR_lmda_04/setup.py
  brainscore_vision/models/CE-SimCLR_lmda_04/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1889 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-SimCLR_lmda_03/__init__.py
  brainscore_vision/models/CE-SimCLR_lmda_03/model.py
  brainscore_vision/models/CE-SimCLR_lmda_03/region_layer_map/CE-SimCLR_lmda_03.json
  brainscore_vision/models/CE-SimCLR_lmda_03/setup.py
  brainscore_vision/models/CE-SimCLR_lmda_03/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1891 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-SimCLR_lmda_05/__init__.py
  brainscore_vision/models/CE-SimCLR_lmda_05/model.py
  brainscore_vision/models/CE-SimCLR_lmda_05/region_layer_map/CE-SimCLR_lmda_05.json
  brainscore_vision/models/CE-SimCLR_lmda_05/setup.py
  brainscore_vision/models/CE-SimCLR_lmda_05/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1879 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-Barlow_lmda_00/__init__.py
  brainscore_vision/models/CE-Barlow_lmda_00/model.py
  brainscore_vision/models/CE-Barlow_lmda_00/region_layer_map/CE-Barlow_lmda_00.json
  brainscore_vision/models/CE-Barlow_lmda_00/setup.py
  brainscore_vision/models/CE-Barlow_lmda_00/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1895 brain-score.org submission (user:437) | (public:False)
  brainscore_vision/models/kap/__init__.py
  brainscore_vision/models/kap/helpers.py
  brainscore_vision/models/kap/load_model.py
  brainscore_vision/models/kap/model.py
  brainscore_vision/models/kap/region_layer_map/kap.json
  brainscore_vision/models/kap/requirements.txt
  brainscore_vision/models/kap/resnet_imagenet_continuoustopo.py
  brainscore_vision/models/kap/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1896 brain-score.org submission (user:437) | (public:False)
  brainscore_vision/models/kap1/__init__.py
  brainscore_vision/models/kap1/helpers.py
  brainscore_vision/models/kap1/load_model.py
  brainscore_vision/models/kap1/model.py
  brainscore_vision/models/kap1/region_layer_map/kap1.json
  brainscore_vision/models/kap1/requirements.txt
  brainscore_vision/models/kap1/resnet_imagenet_continuoustopo.py
  brainscore_vision/models/kap1/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1915 brain-score.org submission (user:437) | (public:False)
  brainscore_vision/models/kapv1/__init__.py
  brainscore_vision/models/kapv1/helpers.py
  brainscore_vision/models/kapv1/load_model.py
  brainscore_vision/models/kapv1/model.py
  brainscore_vision/models/kapv1/region_layer_map/kapv1.json
  brainscore_vision/models/kapv1/requirements.txt
  brainscore_vision/models/kapv1/resnet_imagenet_continuoustopo.py
  brainscore_vision/models/kapv1/test.py
Labels: automerge-web, automerge-approved, trigger-mapping, mapping-complete

#1916 brain-score.org submission (user:437) | (public:False)
  brainscore_vision/models/kapIT/__init__.py
  brainscore_vision/models/kapIT/helpers.py
  brainscore_vision/models/kapIT/load_model.py
  brainscore_vision/models/kapIT/model.py
  brainscore_vision/models/kapIT/region_layer_map/kapIT.json
  brainscore_vision/models/kapIT/requirements.txt
  brainscore_vision/models/kapIT/resnet_imagenet_continuoustopo.py
  brainscore_vision/models/kapIT/test.py
Labels: automerge-web

#1901 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/evresnet_50_8/__init__.py
  brainscore_vision/models/evresnet_50_8/evnet/backends.py
  brainscore_vision/models/evresnet_50_8/evnet/evnet.py
  brainscore_vision/models/evresnet_50_8/evnet/modules.py
  brainscore_vision/models/evresnet_50_8/evnet/params.py
  brainscore_vision/models/evresnet_50_8/evnet/utils.py
  brainscore_vision/models/evresnet_50_8/model.py
  brainscore_vision/models/evresnet_50_8/requirements.txt
  brainscore_vision/models/evresnet_50_8/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1900 brain-score.org submission (user:627) | (public:False)
  brainscore_vision/models/evresnet_50_7/__init__.py
  brainscore_vision/models/evresnet_50_7/evnet/backends.py
  brainscore_vision/models/evresnet_50_7/evnet/evnet.py
  brainscore_vision/models/evresnet_50_7/evnet/modules.py
  brainscore_vision/models/evresnet_50_7/evnet/params.py
  brainscore_vision/models/evresnet_50_7/evnet/utils.py
  brainscore_vision/models/evresnet_50_7/model.py
  brainscore_vision/models/evresnet_50_7/requirements.txt
  brainscore_vision/models/evresnet_50_7/test.py
Labels: automerge-web, automerge-approved, mapping-complete

#1897 brain-score.org submission (user:437) | (public:False)
  brainscore_vision/models/kap2/__init__.py
  brainscore_vision/models/kap2/helpers.py
  brainscore_vision/models/kap2/load_model.py
  brainscore_vision/models/kap2/model.py
  brainscore_vision/models/kap2/region_layer_map/kap2.json
  brainscore_vision/models/kap2/requirements.txt
  brainscore_vision/models/kap2/resnet_imagenet_continuoustopo.py
  brainscore_vision/models/kap2/test.py
Labels: automerge-web, automerge-approved, trigger-mapping, mapping-complete

#1878 custom model submission resnet50_primary_visual_cortex
  brainscore_vision/models/resnet50_primary_visual_cortex/__init__.py
  brainscore_vision/models/resnet50_primary_visual_cortex/model.py
  brainscore_vision/models/resnet50_primary_visual_cortex/region_layer_map/resnet50_primary_visual_cortex.json
  brainscore_vision/models/resnet50_primary_visual_cortex/requirements.txt
  brainscore_vision/models/resnet50_primary_visual_cortex/test.py
Labels: trigger-mapping, mapping-complete

#1881 brain-score.org submission (user:386) | (public:False)
  brainscore_vision/models/CE-MMCR_lmda_03/__init__.py
  brainscore_vision/models/CE-MMCR_lmda_03/model.py
  brainscore_vision/models/CE-MMCR_lmda_03/region_layer_map/CE-MMCR_lmda_03.json
  brainscore_vision/models/CE-MMCR_lmda_03/setup.py
  brainscore_vision/models/CE-MMCR_lmda_03/test.py
Labels: automerge-web, mapping-complete
